"""Deterministic procedural city generation with four morphology families."""

from __future__ import annotations

import hashlib
import heapq
import math
import random
from collections import deque
from dataclasses import asdict, replace
from itertools import pairwise
from typing import Any

from .config import GENERATOR_CONTRACT, CityConfig
from .geometry import road_intersects_xy_box
from .schema import Scene


def derive_seed(root_seed: int, *parts: object) -> int:
    payload = "|".join([str(root_seed), *(str(item) for item in parts)]).encode("utf-8")
    return int.from_bytes(hashlib.sha256(payload).digest()[:8], "big")


def generate_city(config: CityConfig, *, seed: int, name: str = "city") -> Scene:
    """Generate one canonical scene without requiring optional radio/UE packages."""
    rng = random.Random(derive_seed(seed, "city", config.morphology))
    width, depth = config.size_m
    x_edges, y_edges = _street_edges(width, depth, config, rng)
    roads = _roads(width, depth, x_edges, y_edges, config, rng)
    blocks = _blocks(x_edges, y_edges, config.roads.width_m)
    buildings = _buildings(blocks, roads, config, seed, rng)
    base_stations = _base_stations(roads, buildings, width, depth, config, seed, rng)
    tasks = _tasks(roads, width, depth, config, rng)
    max_z = max(
        config.task.altitude_range_m[1],
        config.base_stations.height_m + max((float(item["size_m"][2]) for item in buildings), default=0.0) + 5.0,
        max((float(item["center_m"][2]) + float(item["size_m"][2]) / 2.0 for item in buildings), default=0.0),
    )
    scene_id = _safe_id(f"{name}-{config.morphology}-{seed}")
    scene = Scene(
        schema_version="wireless-city-scene",
        scene_id=scene_id,
        seed=int(seed),
        units="m",
        frame="right-handed,+z-up",
        bounds_min_m=(0.0, 0.0, 0.0),
        bounds_max_m=(float(width), float(depth), float(max_z)),
        roads=roads,
        blocks=blocks,
        buildings=buildings,
        base_stations=base_stations,
        tasks=tasks,
        metadata={
            "generator": "wireless-city-factory",
            "generator_contract": GENERATOR_CONTRACT,
            "morphology": config.morphology,
            "seed_derivation": "sha256(root_seed|city|morphology)",
            "city_config": asdict(config),
            "source_provenance": "Canonical procedural city generated by wireless_city_factory.",
        },
    )
    scene.validate()
    statistics = validate_free_space(
        scene,
        grid_resolution_m=config.validation.grid_resolution_m,
        minimum_largest_component_fraction=config.validation.minimum_largest_component_fraction,
    )
    metadata = dict(scene.metadata)
    metadata["statistics"] = statistics
    metadata["validation"] = {
        "status": "passed",
        "bounds_check": "passed",
        "building_boundary_check": "passed",
        "building_overlap_check": "passed",
        "building_road_clearance_check": "passed",
        "coordinate_check": "passed",
        "free_space_connectivity_check": "passed",
        "task_reachability_check": "passed",
        "base_station_count": len(base_stations),
        "task_count": len(tasks),
    }
    return replace(scene, metadata=metadata).with_fingerprint()


def validate_free_space(
    scene: Scene,
    *,
    grid_resolution_m: float,
    minimum_largest_component_fraction: float,
) -> dict[str, Any]:
    """Validate fixed-altitude free space on a deterministic occupancy grid."""
    if grid_resolution_m <= 0.0:
        raise ValueError("grid_resolution_m must be positive.")
    if not 0.0 <= minimum_largest_component_fraction <= 1.0:
        raise ValueError("minimum_largest_component_fraction must be in [0, 1].")

    city_area = scene.size_m[0] * scene.size_m[1]
    footprints = [float(item["size_m"][0]) * float(item["size_m"][1]) for item in scene.buildings]
    heights = [float(item["size_m"][2]) for item in scene.buildings]
    altitude_results: dict[float, tuple[dict[str, Any], list[bool], list[int], int, int]] = {}
    for altitude in sorted({float(task["start_m"][2]) for task in scene.tasks}):
        altitude_results[altitude] = _free_space_slice(scene, altitude, grid_resolution_m)

    task_paths: list[dict[str, Any]] = []
    for task in scene.tasks:
        altitude = float(task["start_m"][2])
        slice_stats, blocked, labels, nx, ny = altitude_results[altitude]
        start = _point_cell(task["start_m"], grid_resolution_m, nx, ny)
        goal = _point_cell(task["goal_m"], grid_resolution_m, nx, ny)
        start_index = start[1] * nx + start[0]
        goal_index = goal[1] * nx + goal[0]
        reachable = (
            not blocked[start_index]
            and not blocked[goal_index]
            and labels[start_index] == labels[goal_index]
        )
        path_length = _shortest_grid_path(blocked, nx, ny, start, goal, grid_resolution_m) if reachable else None
        result = {
            "task_id": str(task["task_id"]),
            "altitude_m": altitude,
            "start_cell_xy": list(start),
            "goal_cell_xy": list(goal),
            "reachable": reachable,
            "shortest_path_m": None if path_length is None else round(path_length, 6),
        }
        task_paths.append(result)
        if not reachable or path_length is None:
            raise ValueError(f"Task {task['task_id']} is unreachable on the validation grid.")
        if slice_stats["largest_component_fraction"] < minimum_largest_component_fraction:
            raise ValueError(
                "Free space is insufficiently connected at "
                f"z={altitude}: largest component fraction "
                f"{slice_stats['largest_component_fraction']} is below "
                f"{minimum_largest_component_fraction}."
            )

    slices = [altitude_results[key][0] for key in sorted(altitude_results)]
    primary = slices[0]
    return {
        "building_count": len(scene.buildings),
        "footprint_coverage_ratio": round(sum(footprints) / city_area, 9),
        "building_height_m": {
            "minimum": round(min(heights), 6) if heights else None,
            "maximum": round(max(heights), 6) if heights else None,
            "mean": round(sum(heights) / len(heights), 6) if heights else None,
        },
        "free_space_fraction": primary["free_space_fraction"],
        "connected_component_count": primary["connected_component_count"],
        "largest_component_fraction": primary["largest_component_fraction"],
        "free_space_validation": {
            "grid_resolution_m": float(grid_resolution_m),
            "occupancy_rule": "cell-center blocked when building top >= task altitude",
            "connectivity": "8-neighbour, diagonal corner cutting disabled",
            "minimum_largest_component_fraction": float(minimum_largest_component_fraction),
            "altitude_slices": slices,
        },
        "task_paths": task_paths,
    }


def _free_space_slice(
    scene: Scene,
    altitude: float,
    resolution: float,
) -> tuple[dict[str, Any], list[bool], list[int], int, int]:
    width, depth = scene.size_m[:2]
    nx, ny = math.ceil(width / resolution), math.ceil(depth / resolution)
    blocked = [False] * (nx * ny)
    obstacles = []
    for building in scene.buildings:
        center, size = building["center_m"], building["size_m"]
        top = float(center[2]) + float(size[2]) / 2.0
        if top + 1e-7 >= altitude:
            obstacles.append(
                (
                    float(center[0]) - float(size[0]) / 2.0,
                    float(center[0]) + float(size[0]) / 2.0,
                    float(center[1]) - float(size[1]) / 2.0,
                    float(center[1]) + float(size[1]) / 2.0,
                )
            )
    for iy in range(ny):
        y = min(depth, (iy + 0.5) * resolution)
        for ix in range(nx):
            x = min(width, (ix + 0.5) * resolution)
            blocked[iy * nx + ix] = any(x0 <= x <= x1 and y0 <= y <= y1 for x0, x1, y0, y1 in obstacles)

    labels = [-2 if value else -1 for value in blocked]
    component_sizes: list[int] = []
    for index, label in enumerate(labels):
        if label != -1:
            continue
        component_id = len(component_sizes)
        queue = deque([index])
        labels[index] = component_id
        size = 0
        while queue:
            current = queue.popleft()
            size += 1
            x, y = current % nx, current // nx
            for neighbor, _ in _grid_neighbors(blocked, nx, ny, x, y):
                if labels[neighbor] == -1:
                    labels[neighbor] = component_id
                    queue.append(neighbor)
        component_sizes.append(size)
    free_count = len(blocked) - sum(blocked)
    if free_count == 0:
        raise ValueError(f"No free-space cells exist at z={altitude}.")
    largest = max(component_sizes)
    stats = {
        "altitude_m": altitude,
        "grid_shape_yx": [ny, nx],
        "total_cell_count": len(blocked),
        "free_cell_count": free_count,
        "blocked_cell_count": len(blocked) - free_count,
        "free_space_fraction": round(free_count / len(blocked), 9),
        "connected_component_count": len(component_sizes),
        "largest_component_cell_count": largest,
        "largest_component_fraction": round(largest / free_count, 9),
    }
    return stats, blocked, labels, nx, ny


def _point_cell(point: Any, resolution: float, nx: int, ny: int) -> tuple[int, int]:
    return (
        min(nx - 1, max(0, int(float(point[0]) / resolution))),
        min(ny - 1, max(0, int(float(point[1]) / resolution))),
    )


def _grid_neighbors(
    blocked: list[bool],
    nx: int,
    ny: int,
    x: int,
    y: int,
) -> list[tuple[int, float]]:
    result: list[tuple[int, float]] = []
    for dx, dy in ((-1, 0), (1, 0), (0, -1), (0, 1), (-1, -1), (-1, 1), (1, -1), (1, 1)):
        tx, ty = x + dx, y + dy
        if not (0 <= tx < nx and 0 <= ty < ny):
            continue
        target = ty * nx + tx
        if blocked[target]:
            continue
        if dx and dy and (blocked[y * nx + tx] or blocked[ty * nx + x]):
            continue
        result.append((target, math.sqrt(2.0) if dx and dy else 1.0))
    return result


def _shortest_grid_path(
    blocked: list[bool],
    nx: int,
    ny: int,
    start: tuple[int, int],
    goal: tuple[int, int],
    resolution: float,
) -> float | None:
    start_index = start[1] * nx + start[0]
    goal_index = goal[1] * nx + goal[0]
    distances = {start_index: 0.0}
    pending = [(0.0, start_index)]
    while pending:
        distance, current = heapq.heappop(pending)
        if current == goal_index:
            return distance * resolution
        if distance != distances.get(current):
            continue
        x, y = current % nx, current // nx
        for neighbor, cost in _grid_neighbors(blocked, nx, ny, x, y):
            candidate = distance + cost
            if candidate < distances.get(neighbor, math.inf):
                distances[neighbor] = candidate
                heapq.heappush(pending, (candidate, neighbor))
    return None


def _safe_id(value: str) -> str:
    return "".join(char if char.isalnum() or char in "-_." else "_" for char in value)


def _street_edges(width: float, depth: float, config: CityConfig, rng: random.Random) -> tuple[list[float], list[float]]:
    spacing = config.roads.grid_spacing_m
    x_count = max(2, round(width / spacing))
    y_count = max(2, round(depth / spacing))
    x_step, y_step = width / x_count, depth / y_count
    x_edges = [0.0]
    y_edges = [0.0]
    for index in range(1, x_count):
        jitter = 0.0
        if config.morphology in {"bsp_tjunction", "voronoi", "radial_organic"}:
            jitter = rng.uniform(-0.16, 0.16) * x_step
        x_edges.append(max(x_edges[-1] + config.roads.width_m * 1.5, index * x_step + jitter))
    for index in range(1, y_count):
        jitter = 0.0
        if config.morphology in {"bsp_tjunction", "voronoi", "radial_organic"}:
            jitter = rng.uniform(-0.16, 0.16) * y_step
        y_edges.append(max(y_edges[-1] + config.roads.width_m * 1.5, index * y_step + jitter))
    x_edges.append(width)
    y_edges.append(depth)
    return _strict_edges(x_edges, width), _strict_edges(y_edges, depth)


def _strict_edges(values: list[float], upper: float) -> list[float]:
    result = [0.0]
    for value in values[1:-1]:
        if value - result[-1] > 12.0:
            result.append(min(upper - 6.0, value))
    result.append(upper)
    return result


def _irregular_street_nodes(
    width: float,
    depth: float,
    x_edges: list[float],
    y_edges: list[float],
    road_width: float,
    rng: random.Random,
) -> list[list[tuple[float, float]]]:
    """Build a coarse, connected street grid whose junctions do not align."""
    x_positions = x_edges[::2]
    y_positions = y_edges[::2]
    if x_positions[-1] != width:
        x_positions.append(width)
    if y_positions[-1] != depth:
        y_positions.append(depth)

    nodes: list[list[tuple[float, float]]] = []
    for yi, base_y in enumerate(y_positions):
        row: list[tuple[float, float]] = []
        for xi, base_x in enumerate(x_positions):
            x = base_x
            y = base_y
            if 0 < xi < len(x_positions) - 1:
                local_span = min(base_x - x_positions[xi - 1], x_positions[xi + 1] - base_x)
                x += rng.uniform(-0.24, 0.24) * local_span
            if 0 < yi < len(y_positions) - 1:
                local_span = min(base_y - y_positions[yi - 1], y_positions[yi + 1] - base_y)
                y += rng.uniform(-0.24, 0.24) * local_span
            row.append(
                (
                    min(width, max(road_width, x)) if 0 < xi < len(x_positions) - 1 else x,
                    min(depth, max(road_width, y)) if 0 < yi < len(y_positions) - 1 else y,
                )
            )
        nodes.append(row)
    return nodes


def _roads(width: float, depth: float, x_edges: list[float], y_edges: list[float], config: CityConfig, rng: random.Random) -> list[dict[str, Any]]:
    roads: list[dict[str, Any]] = []
    vertical_edges = x_edges if config.morphology in {"manhattan", "bsp_tjunction"} else [0.0, width]
    horizontal_edges = y_edges if config.morphology == "manhattan" else [0.0, depth]
    for index, x in enumerate(vertical_edges):
        roads.append({"road_id": f"road-v-{index:03d}", "kind": "arterial" if index in {0, len(vertical_edges) - 1} else "local", "axis": "x-constant", "start_m": [x, 0.0, 0.0], "end_m": [x, depth, 0.0], "width_m": config.roads.width_m})
    for index, y in enumerate(horizontal_edges):
        roads.append({"road_id": f"road-h-{index:03d}", "kind": "arterial" if index in {0, len(horizontal_edges) - 1} else "local", "axis": "y-constant", "start_m": [0.0, y, 0.0], "end_m": [width, y, 0.0], "width_m": config.roads.width_m})
    if config.morphology == "bsp_tjunction":
        internal_x = x_edges[1:-1]
        for index, (lower_y, upper_y) in enumerate(pairwise(y_edges)):
            if not internal_x:
                break
            y = (lower_y + upper_y) / 2.0
            junction_x = internal_x[index % len(internal_x)]
            start_x, end_x = (0.0, junction_x) if index % 2 == 0 else (junction_x, width)
            roads.append({"road_id": f"road-t-{index:03d}", "kind": "t-junction", "axis": "y-constant", "start_m": [start_x, y, 0.0], "end_m": [end_x, y, 0.0], "width_m": config.roads.width_m * 0.8})
    elif config.morphology == "voronoi":
        nodes = _irregular_street_nodes(
            width,
            depth,
            x_edges,
            y_edges,
            config.roads.width_m,
            rng,
        )
        road_index = 0
        for yi in range(1, len(nodes) - 1):
            for xi in range(len(nodes[yi]) - 1):
                start, end = nodes[yi][xi], nodes[yi][xi + 1]
                roads.append(
                    {
                        "road_id": f"road-irregular-{road_index:03d}",
                        "kind": "collector" if yi % 3 == 0 else "irregular-local",
                        "axis": "irregular",
                        "start_m": [start[0], start[1], 0.0],
                        "end_m": [end[0], end[1], 0.0],
                        "width_m": config.roads.width_m * (0.9 if yi % 3 == 0 else 0.7),
                    }
                )
                road_index += 1
        for xi in range(1, len(nodes[0]) - 1):
            for yi in range(len(nodes) - 1):
                start, end = nodes[yi][xi], nodes[yi + 1][xi]
                roads.append(
                    {
                        "road_id": f"road-irregular-{road_index:03d}",
                        "kind": "collector" if xi % 3 == 0 else "irregular-local",
                        "axis": "irregular",
                        "start_m": [start[0], start[1], 0.0],
                        "end_m": [end[0], end[1], 0.0],
                        "width_m": config.roads.width_m * (0.9 if xi % 3 == 0 else 0.7),
                    }
                )
                road_index += 1
    elif config.morphology == "radial_organic":
        center = (width / 2.0, depth / 2.0)
        for index in range(config.roads.radial_count):
            angle = 2.0 * math.pi * index / config.roads.radial_count
            end = (center[0] + math.cos(angle) * width, center[1] + math.sin(angle) * depth)
            roads.append({"road_id": f"road-radial-{index:03d}", "kind": "radial", "axis": "radial", "start_m": [center[0], center[1], 0.0], "end_m": [min(width, max(0.0, end[0])), min(depth, max(0.0, end[1])), 0.0], "width_m": config.roads.width_m * 0.75})
        for index in range(1, config.roads.ring_count + 1):
            ratio = index / (config.roads.ring_count + 1)
            roads.append({"road_id": f"road-ring-{index:03d}", "kind": "ring", "axis": "ring", "center_m": [center[0], center[1], 0.0], "radius_m": [width * ratio * 0.45, depth * ratio * 0.45], "start_m": [center[0] - width * ratio * 0.45, center[1], 0.0], "end_m": [center[0] + width * ratio * 0.45, center[1], 0.0], "width_m": config.roads.width_m * 0.6})
    return roads


def _blocks(x_edges: list[float], y_edges: list[float], road_width: float) -> list[dict[str, Any]]:
    blocks: list[dict[str, Any]] = []
    for yi in range(len(y_edges) - 1):
        for xi in range(len(x_edges) - 1):
            minimum = (x_edges[xi] + road_width / 2.0 + 1.0, y_edges[yi] + road_width / 2.0 + 1.0)
            maximum = (x_edges[xi + 1] - road_width / 2.0 - 1.0, y_edges[yi + 1] - road_width / 2.0 - 1.0)
            if maximum[0] - minimum[0] >= 8.0 and maximum[1] - minimum[1] >= 8.0:
                blocks.append({"block_id": f"block-{yi:03d}-{xi:03d}", "grid_index": [xi, yi], "minimum_xy_m": [minimum[0], minimum[1]], "maximum_xy_m": [maximum[0], maximum[1]]})
    return blocks


def _buildings(
    blocks: list[dict[str, Any]],
    roads: list[dict[str, Any]],
    config: CityConfig,
    seed: int,
    rng: random.Random,
) -> list[dict[str, Any]]:
    profile = config.building
    areas = [max(0.0, (item["maximum_xy_m"][0] - item["minimum_xy_m"][0]) * (item["maximum_xy_m"][1] - item["minimum_xy_m"][1])) for item in blocks]
    total_area = sum(areas)
    avg_footprint = sum(profile.footprint_min_m) * sum(profile.footprint_max_m) / 4.0
    density_target = round(profile.density_per_km2 * total_area / 1_000_000.0)
    coverage_target = round(profile.coverage_ratio * total_area / max(avg_footprint, 1.0))
    target = max(1 if profile.coverage_ratio > 0 and total_area > 0 else 0, density_target, coverage_target)
    weights = [area / total_area if total_area else 0.0 for area in areas]
    counts = [math.floor(target * weight) for weight in weights]
    remainder = target - sum(counts)
    ranked = sorted(range(len(blocks)), key=lambda index: (-(target * weights[index] - counts[index]), index))
    for index in ranked[:remainder]:
        counts[index] += 1
    buildings: list[dict[str, Any]] = []
    for block, count in zip(blocks, counts):
        minimum = block["minimum_xy_m"]
        maximum = block["maximum_xy_m"]
        available_w = maximum[0] - minimum[0]
        available_d = maximum[1] - minimum[1]
        columns = max(1, math.ceil(math.sqrt(count))) if count else 0
        rows = max(1, math.ceil(count / columns)) if count else 0
        cell_w, cell_d = available_w / columns if columns else 0.0, available_d / rows if rows else 0.0
        emitted = 0
        for row in range(rows):
            for column in range(columns):
                if emitted >= count:
                    break
                if (
                    cell_w < profile.footprint_min_m[0] + profile.separation_m
                    or cell_d < profile.footprint_min_m[1] + profile.separation_m
                ):
                    continue
                for _attempt in range(24):
                    width = min(
                        rng.uniform(profile.footprint_min_m[0], profile.footprint_max_m[0]),
                        cell_w - profile.separation_m,
                    )
                    depth = min(
                        rng.uniform(profile.footprint_min_m[1], profile.footprint_max_m[1]),
                        cell_d - profile.separation_m,
                    )
                    width = max(2.0, width)
                    depth = max(2.0, depth)
                    x_jitter = max(0.0, (cell_w - width - profile.separation_m) / 2.0)
                    y_jitter = max(0.0, (cell_d - depth - profile.separation_m) / 2.0)
                    x = minimum[0] + (column + 0.5) * cell_w + rng.uniform(-x_jitter, x_jitter)
                    y = minimum[1] + (row + 0.5) * cell_d + rng.uniform(-y_jitter, y_jitter)
                    minimum_xy = (x - width / 2.0, y - depth / 2.0)
                    maximum_xy = (x + width / 2.0, y + depth / 2.0)
                    if any(
                        road_intersects_xy_box(road, minimum_xy, maximum_xy)
                        for road in roads
                    ):
                        continue
                    height = _height(profile, rng)
                    building_id = f"building-{len(buildings):05d}"
                    buildings.append({"building_id": building_id, "block_id": block["block_id"], "center_m": [x, y, height / 2.0], "size_m": [width, depth, height], "material": "concrete", "height_distribution": profile.height_distribution})
                    emitted += 1
                    break
    return buildings


def _height(profile: Any, rng: random.Random) -> float:
    if profile.height_distribution == "uniform":
        value = rng.uniform(profile.height_min_m, profile.height_max_m)
    elif profile.height_distribution == "normal":
        value = rng.gauss(profile.height_mean_m, profile.height_std_m)
    else:
        sigma = math.log(max(1.01, profile.height_std_m / max(profile.height_mean_m, 1.0) + 1.0))
        value = rng.lognormvariate(math.log(max(profile.height_mean_m, 1.0)), sigma)
    return min(profile.height_max_m, max(profile.height_min_m, value))


def _base_stations(roads: list[dict[str, Any]], buildings: list[dict[str, Any]], width: float, depth: float, config: CityConfig, seed: int, rng: random.Random) -> list[dict[str, Any]]:
    spec = config.base_stations
    placement_seed = derive_seed(seed, "base-stations", spec.placement_family)
    placement_rng = random.Random(placement_seed)
    target = max(1 if spec.density_per_km2 > 0 else 0, round(spec.density_per_km2 * width * depth / 1_000_000.0))
    candidates: list[tuple[float, float, float, str | None]] = []
    if spec.placement_family in {"rooftop_grid", "random_rooftop"}:
        order = list(range(len(buildings)))
        if spec.placement_family == "random_rooftop":
            placement_rng.shuffle(order)
        else:
            order.sort(key=lambda index: (float(buildings[index]["center_m"][1]), float(buildings[index]["center_m"][0])))
        for index in order:
            building = buildings[index]
            top = float(building["center_m"][2]) + float(building["size_m"][2]) / 2.0
            if spec.height_reference == "absolute_agl" and top + 1.0 > spec.height_m:
                continue
            x, y = float(building["center_m"][0]), float(building["center_m"][1])
            offset_x = offset_y = 0.0
            if spec.placement_family == "random_rooftop" and spec.random_offset_m > 0.0:
                max_x = min(spec.random_offset_m, max(0.0, float(building["size_m"][0]) / 2.0 - 0.5))
                max_y = min(spec.random_offset_m, max(0.0, float(building["size_m"][1]) / 2.0 - 0.5))
                offset_x = placement_rng.uniform(-max_x, max_x)
                offset_y = placement_rng.uniform(-max_y, max_y)
            antenna_z = (
                spec.height_m
                if spec.height_reference == "absolute_agl"
                else top + spec.height_m
            )
            candidates.append(
                (x + offset_x, y + offset_y, antenna_z, str(building["building_id"]))
            )
    else:
        sample_spacing = min(50.0, max(10.0, spec.min_separation_m / 3.0))
        seen: set[tuple[float, float]] = set()
        for road in roads:
            if road.get("axis") == "ring":
                center, radii = road["center_m"], road["radius_m"]
                rx, ry = float(radii[0]), float(radii[1])
                circumference = math.pi * (
                    3.0 * (rx + ry) - math.sqrt((3.0 * rx + ry) * (rx + 3.0 * ry))
                )
                count = max(12, math.ceil(circumference / sample_spacing))
                points = [
                    (
                        float(center[0]) + rx * math.cos(2.0 * math.pi * index / count),
                        float(center[1]) + ry * math.sin(2.0 * math.pi * index / count),
                    )
                    for index in range(count)
                ]
            else:
                start, end = road["start_m"], road["end_m"]
                dx = float(end[0]) - float(start[0])
                dy = float(end[1]) - float(start[1])
                count = max(1, math.ceil(math.hypot(dx, dy) / sample_spacing))
                points = [
                    (
                        float(start[0]) + dx * index / count,
                        float(start[1]) + dy * index / count,
                    )
                    for index in range(count + 1)
                ]
            for x, y in points:
                key = (round(x, 6), round(y, 6))
                if key not in seen:
                    seen.add(key)
                    candidates.append((x, y, spec.height_m, None))
        candidates = _spaced_street_site_order(
            candidates,
            spec.min_separation_m,
            target,
            width,
            depth,
        )
    stations: list[dict[str, Any]] = []
    for x, y, z, host in candidates:
        if len(stations) >= target:
            break
        if any(math.hypot(x - float(item["position_m"][0]), y - float(item["position_m"][1])) < spec.min_separation_m for item in stations):
            continue
        station_id = f"bs-{len(stations):03d}"
        host_building = next(
            (item for item in buildings if item["building_id"] == host),
            None,
        )
        host_center = host_building["center_m"] if host_building is not None else [x, y, 0.0]
        roof_z = (
            float(host_building["center_m"][2]) + float(host_building["size_m"][2]) / 2.0
            if host_building is not None
            else 0.0
        )
        mast_height_m = z - roof_z
        sectors = [
            {
                "sector_id": f"{station_id}-sector-{index:02d}",
                "sector_index": index,
                "azimuth_deg": float(azimuth) % 360.0,
                "downtilt_deg": spec.downtilt_deg,
                "nominal_tx_power_dbm": spec.power_dbm,
                "carrier_frequency_hz": spec.carrier_frequency_hz,
                "bandwidth_hz": spec.bandwidth_hz,
            }
            for index, azimuth in enumerate(spec.sector_azimuths_deg)
        ]
        station = {
            "base_station_id": station_id,
            "deployment_profile": spec.deployment_profile,
            "preset_id": spec.preset_id,
            "preset_version": spec.preset_version,
            "position_m": [x, y, z],
            "antenna_height_m": z,
            "antenna_height_agl_m": z,
            "nominal_tx_power_dbm": spec.power_dbm,
            "carrier_frequency_hz": spec.carrier_frequency_hz,
            "bandwidth_hz": spec.bandwidth_hz,
            "antenna_model": spec.antenna_model,
            "host_building_id": host,
            "sector_count": len(sectors),
            "sectors": sectors,
            "metadata": {
                "source_preset_id": spec.source_preset_id,
                "modified_fields": list(spec.modified_fields),
                "function_type": spec.function_type,
                "source_evidence_level": spec.source_evidence_level,
                "parameter_status": spec.parameter_status,
                "applicable_scenarios": list(spec.applicable_scenarios),
                "polarization": spec.polarization,
                "duplex_mode": spec.duplex_mode,
                "sensing_enabled": spec.sensing_enabled,
                "sensing_waveform_class": spec.sensing_waveform_class,
                "placement_family": spec.placement_family,
                "height_reference": spec.height_reference,
                "mast_height_m": mast_height_m,
                "minimum_separation_m": spec.min_separation_m,
                "reference_inter_site_distance_m": spec.reference_inter_site_distance_m,
                "reference_source": spec.reference_source,
                "offset_xy_m": [x - float(host_center[0]), y - float(host_center[1])],
                "placement_seed": placement_seed,
            },
        }
        stations.append(station)
    if len(stations) != target:
        raise ValueError(
            f"Base-station placement produced {len(stations)} sites but configuration requires {target}."
        )
    return stations


def _spaced_street_site_order(
    candidates: list[tuple[float, float, float, str | None]],
    minimum_separation_m: float,
    target: int,
    width: float,
    depth: float,
) -> list[tuple[float, float, float, str | None]]:
    """Choose a deterministic road-site packing without relaxing separation."""
    if not candidates or target <= 0:
        return []
    center = (width / 2.0, depth / 2.0)
    seed_indices = sorted(
        range(len(candidates)),
        key=lambda index: (
            math.hypot(candidates[index][0] - center[0], candidates[index][1] - center[1]),
            candidates[index][1],
            candidates[index][0],
        ),
    )
    best: list[tuple[float, float, float, str | None]] = []
    for seed_index in seed_indices:
        selected = [candidates[seed_index]]
        remaining = [
            candidate for index, candidate in enumerate(candidates) if index != seed_index
        ]
        while remaining and len(selected) < target:
            eligible = [
                candidate
                for candidate in remaining
                if all(
                    math.hypot(candidate[0] - item[0], candidate[1] - item[1])
                    >= minimum_separation_m
                    for item in selected
                )
            ]
            if not eligible:
                break
            next_candidate = max(
                eligible,
                key=lambda candidate: (
                    min(
                        math.hypot(candidate[0] - item[0], candidate[1] - item[1])
                        for item in selected
                    ),
                    -candidate[1],
                    -candidate[0],
                ),
            )
            selected.append(next_candidate)
            remaining.remove(next_candidate)
        if len(selected) > len(best):
            best = selected
        if len(best) >= target:
            return best
    return best


def _tasks(roads: list[dict[str, Any]], width: float, depth: float, config: CityConfig, rng: random.Random) -> list[dict[str, Any]]:
    if roads:
        horizontal = [item for item in roads if item.get("axis") == "y-constant"]
    else:
        horizontal = []
    tasks: list[dict[str, Any]] = []
    for index in range(config.task.count):
        if config.task.start_xy_m is not None and config.task.goal_xy_m is not None:
            start_xy = config.task.start_xy_m
            goal_xy = config.task.goal_xy_m
        elif len(horizontal) >= 2:
            ordered = sorted(horizontal, key=lambda item: float(item["start_m"][1]))
            last = len(ordered) - 1
            start_road = ordered[(round(last * 0.2) + index) % len(ordered)]
            goal_road = ordered[(round(last * 0.8) - index) % len(ordered)]
            if start_road is goal_road:
                goal_road = ordered[(ordered.index(goal_road) + max(1, len(ordered) // 2)) % len(ordered)]
            start_xy = (width * 0.15, float(start_road["start_m"][1]))
            goal_xy = (width * 0.85, float(goal_road["start_m"][1]))
        else:
            start_xy, goal_xy = (width * 0.15, depth * 0.15), (width * 0.85, depth * 0.85)
        if index % 2:
            start_xy, goal_xy = goal_xy, start_xy
        tasks.append(
            {
                "task_id": f"task-{index:03d}",
                "start_m": [start_xy[0], start_xy[1], config.task.altitude_m],
                "goal_m": [goal_xy[0], goal_xy[1], config.task.altitude_m],
                "altitude_range_m": list(config.task.altitude_range_m),
                "selection_mode": config.task.selection_mode,
                "constraint_preset": config.task.constraint_preset,
                "minimum_sinr_db": config.task.minimum_sinr_db,
                "minimum_rss_dbm": config.task.minimum_rss_dbm,
                "maximum_outage_fraction": config.task.maximum_outage_fraction,
                "mission_seed": derive_seed(config.task.count, "mission", index),
            }
        )
    return tasks
